apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hailo-exporter
  namespace: monitoring
  labels:
    app: hailo-exporter
spec:
  selector:
    matchLabels:
      app: hailo-exporter
  template:
    metadata:
      labels:
        app: hailo-exporter
    spec:
      nodeSelector:
        device: rpi
      initContainers:
        - name: init-hmon-dir
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - mkdir -p /tmp/hmon_files && chmod 777 /tmp/hmon_files
          volumeMounts:
            - name: hmon-volume
              mountPath: /tmp/hmon_files
      containers:
        - name: hailo-exporter
          image: yjh2353693/hailo-exporter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9102
              name: metrics
          volumeMounts:
            - name: hmon-volume
              mountPath: /tmp/hmon_files
              readOnly: false
      volumes:
        - name: hmon-volume
          hostPath:
            path: /tmp/hmon_files
            type: DirectoryOrCreate
